title: iffinity docs
theme: just-the-docs

aux_links:
    GitHub Repo: https://github.com/zehanort/iffinity/

url: https://zehanort.github.io
baseurl: /iffinity

color_scheme: dark

logo: "/assets/images/logo-dark-theme.png"
favicon_ico: "/assets/images/favicon.ico"
